import rtconfig

from building import *

cwd = GetCurrentDir()

src = Glob('*.c') + Glob('LCD/*.c')

CPPDEFINES=[]
CPPPATH = [cwd, cwd + '/LCD']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
