#ifndef LCD_UI_CORE_H
#define LCD_UI_CORE_H

#include <rtthread.h>

typedef enum
{
    LCD_PAGE_HOME = 0,
    LCD_PAGE_MAIN_MENU,
    LCD_PAGE_DRIVE_RECORD_MENU,
    LCD_PAGE_DEVICE_STATUS_MENU,
    LCD_PAGE_SYSTEM_SETTING_MENU,
    LCD_PAGE_DRIVE_RECORD_FATIGUE,
    LCD_PAGE_DRIVE_RECORD_LOCATION,
    LCD_PAGE_DRIVE_RECORD_MILEAGE,
    LCD_PAGE_DRIVE_RECORD_DRIVER_INFO,
    LCD_PAGE_DRIVE_RECORD_VEHICLE_INFO,
    LCD_PAGE_DRIVE_RECORD_LOAD_STATUS,
    LCD_PAGE_DRIVE_RECORD_LOAD_STATUS_OK,
    LCD_PAGE_DRIVE_RECORD_EXPORT,
    LCD_PAGE_DRIVE_RECORD_INFO_CENTER,
    LCD_PAGE_DRIVE_RECORD_INFO_CENTER_TEXT,
    LCD_PAGE_DRIVE_RECORD_INFO_CENTER_BROADCAST,
    LCD_PAGE_DRIVE_RECORD_INFO_CENTER_EVENT_REPORT,
    LCD_PAGE_DRIVE_RECORD_INFO_CENTER_EWAYBILL,
    LCD_PAGE_DRIVE_RECORD_INFO_CENTER_TEXT_DISPATCH,
    LCD_PAGE_DRIVE_RECORD_INFO_CENTER_TEXT_NORMAL,
    LCD_PAGE_DRIVE_RECORD_INFO_CENTER_TEXT_FAULT,
    LCD_PAGE_DRIVE_RECORD_INFO_CENTER_TEXT_EMERGENCY,
    LCD_PAGE_DRIVE_RECORD_VIN,
    LCD_PAGE_DEVICE_STATUS_VERSION,
    LCD_PAGE_DEVICE_STATUS_GFRS,
    LCD_PAGE_DEVICE_STATUS_SELF_TEST,
    LCD_PAGE_DEVICE_STATUS_LOCATION_MODULE,
    LCD_PAGE_DEVICE_STATUS_VEHICLE,
    LCD_PAGE_DEVICE_STATUS_STORAGE,
    LCD_PAGE_DEVICE_STATUS_AV,
    LCD_PAGE_DEVICE_STATUS_SPEED,
    LCD_PAGE_DEVICE_STATUS_DRIVER_MONITOR,
    LCD_PAGE_SYSTEM_SETTING_KEY_VOLUME,
    LCD_PAGE_COMMON_CONFIG_OK,
    LCD_PAGE_SYSTEM_SETTING_BRIGHTNESS,
    LCD_PAGE_SYSTEM_SETTING_BACKLIGHT_TIME,
    LCD_PAGE_SYSTEM_SETTING_BRIGHTNESS_LEVEL,
    LCD_PAGE_SYSTEM_SETTING_VEHICLE_INFO,
    LCD_PAGE_SYSTEM_SETTING_VEHICLE_INFO_VIN,
    LCD_PAGE_SYSTEM_SETTING_VEHICLE_INFO_PLATE_SET,
    LCD_PAGE_SYSTEM_SETTING_VEHICLE_INFO_PLATE_COLOR,
    LCD_PAGE_SYSTEM_SETTING_VEHICLE_INFO_PLATE_CLASS,
    LCD_PAGE_SYSTEM_SETTING_VEHICLE_INFO_PROVINCE_ID,
    LCD_PAGE_SYSTEM_SETTING_VEHICLE_INFO_CITY_ID,
    LCD_PAGE_SYSTEM_SETTING_HOST_PARAM,
    LCD_PAGE_SYSTEM_SETTING_HOST_PARAM_LOCAL_PHONE,
    LCD_PAGE_SYSTEM_SETTING_HOST_PARAM_SOS_PHONE,
    LCD_PAGE_SYSTEM_SETTING_HOST_PARAM_SERVER1,
    LCD_PAGE_SYSTEM_SETTING_HOST_PARAM_SERVER2,
    LCD_PAGE_SYSTEM_SETTING_INIT_MILEAGE,
    LCD_PAGE_SYSTEM_SETTING_REGISTER,
    LCD_PAGE_SYSTEM_SETTING_UNREGISTER,
    LCD_PAGE_SYSTEM_SETTING_REC_VER,
    LCD_PAGE_SYSTEM_SETTING_COMPONENT_VER,
    LCD_PAGE_MAX
} lcd_page_id_t;

typedef enum
{
    LCD_PAGE_KIND_VIEW = 0,
    LCD_PAGE_KIND_LIST,
    LCD_PAGE_KIND_ACTION_RESULT
} lcd_page_kind_t;

typedef struct
{
    lcd_page_id_t page_id;
    lcd_page_id_t parent_id;
    lcd_page_kind_t kind;
    const lcd_page_id_t *children;
    uint8_t child_count;
    uint8_t select_count;
    rt_bool_t show_title;
    void (*render)(void);
    void (*on_confirm)(void);
    uint32_t auto_return_ms;
    lcd_page_id_t auto_return_target;
} lcd_page_node_t;

void lcd_ui_core_reset(void);

rt_bool_t *lcd_ui_core_menu_mode_mutable(void);
lcd_page_id_t *lcd_ui_core_current_page_mutable(void);
uint8_t *lcd_ui_core_page_selected_mutable(void);
rt_tick_t *lcd_ui_core_page_enter_tick_mutable(void);
rt_bool_t *lcd_ui_core_need_redraw_mutable(void);
lcd_page_id_t *lcd_ui_core_common_ok_return_page_mutable(void);

#endif /* LCD_UI_CORE_H */
